services:
  - type: web
    name: copo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn COPOS.opos.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: copo-db
          property: connectionString

databases:
  - name: copo-db
    plan: free
